# Generated by Django 4.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("is_superuser", models.BooleanField(default=False)),
                ("id_user", models.AutoField(db_column="id_user", primary_key=True, serialize=False)),
                ("role", models.CharField(choices=[("admin", "Admin"), ("driver", "Driver"), ("rider", "Rider")], max_length=50)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(blank=True, max_length=50)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "rides_user",
            },
        ),
        migrations.CreateModel(
            name="Ride",
            fields=[
                ("id_ride", models.AutoField(db_column="id_ride", primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("en-route", "En route"), ("pickup", "Pickup"), ("dropoff", "Dropoff")], max_length=50)),
                ("pickup_latitude", models.FloatField()),
                ("pickup_longitude", models.FloatField()),
                ("dropoff_latitude", models.FloatField(blank=True, null=True)),
                ("dropoff_longitude", models.FloatField(blank=True, null=True)),
                ("pickup_time", models.DateTimeField()),
                ("id_driver", models.ForeignKey(db_column="id_driver", on_delete=django.db.models.deletion.CASCADE, related_name="rides_as_driver", to=settings.AUTH_USER_MODEL)),
                ("id_rider", models.ForeignKey(db_column="id_rider", on_delete=django.db.models.deletion.CASCADE, related_name="rides_as_rider", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "rides_ride",
                "ordering": ["-pickup_time"],
            },
        ),
        migrations.CreateModel(
            name="RideEvent",
            fields=[
                ("id_ride_event", models.AutoField(db_column="id_ride_event", primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("id_ride", models.ForeignKey(db_column="id_ride", on_delete=django.db.models.deletion.CASCADE, related_name="ride_events", to="rides.ride")),
            ],
            options={
                "db_table": "rides_ride_event",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="appuser",
            name="groups",
            field=models.ManyToManyField(blank=True, help_text="The groups this user belongs to.", related_name="user_set", related_query_name="user", to="auth.group", verbose_name="groups"),
        ),
        migrations.AddField(
            model_name="appuser",
            name="user_permissions",
            field=models.ManyToManyField(blank=True, help_text="Specific permissions for this user.", related_name="user_set", related_query_name="user", to="auth.permission", verbose_name="user permissions"),
        ),
    ]
